<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actividad 4</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        header {
            background-color: green;
            color: #fff;
            text-align: center;
            padding: 20px 0;
        }
        main {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            margin: 0;
        }
        h2 {
            margin: 0;
            text-align: center;
        }
        h3 {
            margin: 0;
            text-align: center;
        }
        section {
            margin-bottom: 20px;
        }
        footer {
            text-align: center;
            padding: 10px 0;
            background-color: #007bff;
            color: #fff;
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
        }
    </style>
</head>
<body>
    <header>
        <h1>Actividad 5</h1>
    </header>
    <main>
        <section>
            <h2>Universidad Externado de Colombia</h2>
            <h3>Ciencia de Datos</h3>
            <h3>Métodos Numéricos</h3>
        </section>
    </main>
    <footer>
        <p>&copy; 2024 Universidad Externado de Colombia - Ciencia de Datos</p>
    </footer>
</body>
</html>


## Librerías

In [1]:
import numpy as np
import math
import plotly.express as px
import time
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp
from sympy.abc import x


## Funciones

## Preguntas

**1. Determine cuáles de las siguientes matrices son:**

- (a) Simétricas
- (b) Singulares
- (c) Definidas positivas


Matrices:
- $\begin{pmatrix} 2 & 1 \\ 1 & 3 \end{pmatrix}$

In [5]:
matrizA = np.array([[2, 1], [1, 3]])
np.array_equal(matrizA, matrizA.T) #La matriz original es igual a la matriz traspuesta.

True

In [14]:
valores_propios, vectores_propios = np.linalg.eig(matrizA)
valores_propios

array([1.38196601, 3.61803399])

- $\begin{pmatrix} 2 & 1 & 0 \\ 0 & 3 & 0 \\ 1 & 0 & 4 \end{pmatrix}$

In [7]:
matrizB = np.array([[2, 1, 0], [0, 3, 0], [1, 0, 4]])
np.array_equal(matrizB, matrizB.T) #La matriz original no es igual a la matriz traspuesta. No es simétrica

False

In [15]:
valores_propios, vectores_propios = np.linalg.eig(matrizB)
valores_propios

array([4., 2., 3.])

- $\begin{pmatrix} 4 & 2 & 6 \\ 3 & 0 & 7 \\ -2 & -1 & -3 \end{pmatrix}$

In [10]:
matrizC = np.array([[4, 2, 6], [3, 0, 7], [-2, -1, -3]])
np.array_equal(matrizC, matrizC.T) #La matriz original no es igual a la matriz traspuesta. No es simétrica

False

In [18]:
valores_propios, vectores_propios = np.linalg.eig(matrizC)
valores_propios

array([1., 1., 7., 4.])

- $\begin{pmatrix} 4 & 0 & 0 & 0 \\ 6 & 7 & 0 & 0 \\ 9 & 11 & 1 & 0 \\ 5 & 4 & 1 & 1 \end{pmatrix}$

In [19]:
matrizD = np.array([[4, 0, 0, 0], [6, 7, 0,0], [9, 11, 1, 0], [5, 4, 1, 1]])
np.array_equal(matrizD, matrizD.T) #La matriz original no es igual a la matriz traspuesta. No es simétrica

False

In [20]:
valores_propios, vectores_propios = np.linalg.eig(matrizD)
valores_propios

array([1., 1., 7., 4.])

**2. Utilice el algoritmo de factorización LDLT para encontrar una factorización para las siguientes matrices:**

- $\begin{pmatrix} 4 & -1 & 1 \\ -1 & 3 & 0 \\ 1 & 0 & 2 \end{pmatrix}$

- $\begin{pmatrix} 4 & 2 & 2 \\ 2 & 6 & 2 \\ 2 & 2 & 5 \end{pmatrix}$

- $\begin{pmatrix} 4 & 1 & 1 & 1 \\ 1 & 3 & 0 & -1 \\ 1 & 0 & 2 & 1 \\ 1 & -1 & 1 & 4 \end{pmatrix}$

- $\begin{pmatrix} 6 & 2 & 1 & -1 \\ 2 & 4 & 1 & 0 \\ 1 & 1 & 4 & -1 \\ -1 & 0 & -1 & 3 \end{pmatrix}$

**3. Utilice el algoritmo de Cholesky para encontrar una factorización de la forma LLT para las matrices anteriores.**

**4. Encuentre todas las $\alpha$ de tal forma que $A = \begin{pmatrix} \alpha & 1 & -1 \\ 1 & 2 & 1 \\ -1 & 1 & 4 \end{pmatrix}$ sea definida positiva.**

**5. Considere las siguientes matrices. Encuentre la matriz de permutación $P$ tal que $PA$ se puede factorizar en el producto $LU$ donde $L$ es triangular inferior con unos en su diagonal y $U$ es triangular superior para estas matrices:**

- $\begin{pmatrix} 1 & 2 & -1 \\ 2 & 4 & 0 \\ 0 & 1 & -1 \end{pmatrix}$

- $\begin{pmatrix} 0 & 1 & 1 \\ 1 & -2 & -1 \\ 1 & -1 & 1 \end{pmatrix}$

- $\begin{pmatrix} 1 & 1 & -1 & 0 \\ 1 & 2 & 1 & 4 \\ -1 & 2 & -1 & 2 \\ 0 & 4 & 3 & 3 \end{pmatrix}$

**6. Modifique el algoritmo de factorización LU de tal forma que se pueda utilizar para resolver un sistema lineal y resuélvalo.**

(a)
- $2x_1 - x_2 + x_3 = -1$
- $3x_1 + 3x_2 + 9x_3 = 0$
- $3x_1 + 3x_2 + 5x_3 = 4$

(b)
- $2.1756x_1 + 4.0231x_2 - 2.1732x_3 + 5.1967x_4 = 17.102$
- $-4.0231x_1 + 6.0000x_2 + 1.1973x_4 = -6.1593$
- $-1.0000x_1 - 5.2107x_2 + 1.1111x_3 = 3.0004$
- $6.0235x_1 + 7.0000x_2 - 4.1561x_4 = 0.0000$