In [7]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

suma = A + B
print("Suma de matrices:\n", suma)

resta = A - B
print("Resta de matrices:\n", resta)

producto_elemento = A * B
print("Multiplicación elemento a elemento:\n", producto_elemento)

producto_matricial = np.dot(A, B)
print("Multiplicación de matrices:\n", producto_matricial)

producto_matricial_v2 = A @ B
print("Multiplicación de matrices (versión reciente de NumPy):\n", producto_matricial_v2)

division = A / B
print("División elemento a elemento:\n", division)

transpuesta = A.T
print("Transpuesta de A:\n", transpuesta)

inversa = np.linalg.inv(A)
print("Inversa de A:\n", inversa)

determinante = np.linalg.det(A)
print("Determinante de A:", determinante)

Suma de matrices:
 [[ 6  8]
 [10 12]]
Resta de matrices:
 [[-4 -4]
 [-4 -4]]
Multiplicación elemento a elemento:
 [[ 5 12]
 [21 32]]
Multiplicación de matrices:
 [[19 22]
 [43 50]]
Multiplicación de matrices (versión reciente de NumPy):
 [[19 22]
 [43 50]]
División elemento a elemento:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Transpuesta de A:
 [[1 3]
 [2 4]]
Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinante de A: -2.0000000000000004


In [8]:
import sympy as sp

x = sp.symbols('x')

f = x**2 + 3*x + 2

derivada = sp.diff(f, x)

print("La derivada de f respecto a x es:", derivada)


La derivada de f respecto a x es: 2*x + 3


In [9]:

integral_definida = sp.integrate(f, (x, 0, 1))

print("La integral definida de f desde 0 hasta 1 es:", integral_definida)

La integral definida de f desde 0 hasta 1 es: 23/6


In [10]:
import sympy as sp

x = sp.symbols('x')

f = sp.sin(x**2)

derivada = sp.diff(f, x)
print("Derivada de f respecto a x:", derivada)

integral_indefinida = sp.integrate(f, x)
print("Integral indefinida de f respecto a x:", integral_indefinida)

integral_definida = sp.integrate(f, (x, 0, sp.pi))
print("Integral definida de f desde 0 hasta pi:", integral_definida)

Derivada de f respecto a x: 2*x*cos(x**2)
Integral indefinida de f respecto a x: 3*sqrt(2)*sqrt(pi)*fresnels(sqrt(2)*x/sqrt(pi))*gamma(3/4)/(8*gamma(7/4))
Integral definida de f desde 0 hasta pi: 3*sqrt(2)*sqrt(pi)*fresnels(sqrt(2)*sqrt(pi))*gamma(3/4)/(8*gamma(7/4))


In [28]:
import sympy as sp
import math

x = sp.symbols('x')
x0 = math.pi/4  

f = math.sin(x)

n = 5  #

polinomio_taylor = sp.series(f, x, x0, n+1).removeO()

print(f"Polinomio de Taylor de {f} alrededor de x = {x0} hasta el orden {n}:")
print(polinomio_taylor)


TypeError: Cannot convert expression to float

In [16]:
A = np.array([[1, 4], [2,-1], [0,3]])
B = np.array([[5, 6], [7, 8]])

In [17]:
transpuesta = A.T

In [18]:
transpuesta

array([[ 1,  2,  0],
       [ 4, -1,  3]])

In [21]:
A * A.T

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [23]:
A 

array([[ 1, 16],
       [ 4,  1],
       [ 0,  9]])

In [25]:
4*3*2

24

In [30]:
math.pi/4

0.7853981633974483

In [31]:
0.73135 - 0.03496585

0.69638415

In [32]:
5/7

0.7142857142857143

In [33]:
(5/7) + (1/3)

1.0476190476190477

In [34]:
abs(((5/7) + (1/3)) - 0.380952)

0.6666670476190477

In [35]:
abs(((5/7) + (1/3)) - 0.380952)/((5/7) + (1/3))

0.636364

In [46]:
((5/7) + (1/3))/((0.111111)*(0.0001))

94285.80857152285

In [38]:
10(**-4)

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
/var/folders/qh/5z05jrd51bj_b5b8cvk1q0gh0000gn/T/ipykernel_65342/512911303.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  10(**-4)


TypeError: 10 argument after ** must be a mapping, not int

In [43]:
1/(10*(4))

0.025

In [45]:
0.11111

0.0001

In [47]:
((5/7)-(1/3))/(0.111111*0.0001)

34285.74857146286

In [48]:
0.111111*0.0001

1.1111100000000001e-05

In [53]:
abs((34285.74857146286) - ((0.380952)/(0.000111)))/(34285.74857146286)

0.8999001001

In [54]:
((5/7)-(1/3))*(0.111111*0.0001)

4.2328e-06