In [21]:
import numpy as np
import math

In [22]:
matrizA = np.array([[ 4, -1,  0,  0,  0], [-1,  4, -1,  0,  0],[ 0, -1,  4, -1,  0],[ 0,  0, -1,  4, -1],[ 0,  0,  0, -1,  4]])
vectorB = np.array([[ 1.],[-math.pi],[0.],[math.pi],[0.]])
vectorCerosAntes = np.array([0] * 5)

In [28]:
iteracion = 0
while True:
    print("polo", iteracion)
    iteracion += 1
    xNueva = vectorCerosAntes.copy()
    for i in range(5):
        # Según yo ambas sumatorias van a dar un número negativo porque se multiplica en el primer caso -ai* xj elveado a la k, para k para darría positivos así que el producto da negativo en la primera sumatoria. En la segunda ya es negativa
        vectorCerosAntes[i] = (1 - 1.0518) * xNueva[i] + (1.0518 / matrizA[i, i])*((-1*np.dot(matrizA[i, :i], vectorCerosAntes[:i])) - np.dot(matrizA[i, i + 1:], xNueva[i + 1:] ) + vectorB[i])
    print(vectorCerosAntes)
    if (np.linalg.norm(xNueva - vectorCerosAntes)/np.linalg.norm(vectorCerosAntes)) < 1e-4: 
        print("se acabó") 
        break

polo 0
[0 0 0 0 0]
polo 1
[0 0 0 0 0]
polo 2
[0 0 0 0 0]
polo 3
[0 0 0 0 0]
polo 4
[0 0 0 0 0]
polo 5
[0 0 0 0 0]
polo 6
[0 0 0 0 0]
polo 7
[0 0 0 0 0]
polo 8
[0 0 0 0 0]
polo 9
[0 0 0 0 0]
polo 10
[0 0 0 0 0]
polo 11
[0 0 0 0 0]
polo 12
[0 0 0 0 0]
polo 13
[0 0 0 0 0]
polo 14
[0 0 0 0 0]
polo 15
[0 0 0 0 0]
polo 16
[0 0 0 0 0]
polo 17
[0 0 0 0 0]
polo 18
[0 0 0 0 0]
polo 19
[0 0 0 0 0]
polo 20
[0 0 0 0 0]
polo 21
[0 0 0 0 0]
polo 22
[0 0 0 0 0]
polo 23
[0 0 0 0 0]
polo 24
[0 0 0 0 0]
polo 25
[0 0 0 0 0]
polo 26
[0 0 0 0 0]
polo 27
[0 0 0 0 0]
polo 28
[0 0 0 0 0]
polo 29
[0 0 0 0 0]
polo 30
[0 0 0 0 0]
polo 31
[0 0 0 0 0]
polo 32
[0 0 0 0 0]
polo 33
[0 0 0 0 0]
polo 34
[0 0 0 0 0]
polo 35
[0 0 0 0 0]
polo 36
[0 0 0 0 0]
polo 37
[0 0 0 0 0]
polo 38
[0 0 0 0 0]
polo 39
[0 0 0 0 0]
polo 40
[0 0 0 0 0]
polo 41
[0 0 0 0 0]
polo 42
[0 0 0 0 0]
polo 43
[0 0 0 0 0]
polo 44
[0 0 0 0 0]
polo 45
[0 0 0 0 0]
polo 46
[0 0 0 0 0]
polo 47
[0 0 0 0 0]
polo 48
[0 0 0 0 0]
polo 49
[0 0 0 0 0]
polo 50
[0

/var/folders/qh/5z05jrd51bj_b5b8cvk1q0gh0000gn/T/ipykernel_1602/3027801964.py:10: RuntimeWarning: invalid value encountered in double_scalars
  if (np.linalg.norm(xNueva - vectorCerosAntes)/np.linalg.norm(vectorCerosAntes)) < 1e-4:


polo 1419
[0 0 0 0 0]
polo 1420
[0 0 0 0 0]
polo 1421
[0 0 0 0 0]
polo 1422
[0 0 0 0 0]
polo 1423
[0 0 0 0 0]
polo 1424
[0 0 0 0 0]
polo 1425
[0 0 0 0 0]
polo 1426
[0 0 0 0 0]
polo 1427
[0 0 0 0 0]
polo 1428
[0 0 0 0 0]
polo 1429
[0 0 0 0 0]
polo 1430
[0 0 0 0 0]
polo 1431
[0 0 0 0 0]
polo 1432
[0 0 0 0 0]
polo 1433
[0 0 0 0 0]
polo 1434
[0 0 0 0 0]
polo 1435
[0 0 0 0 0]
polo 1436
[0 0 0 0 0]
polo 1437
[0 0 0 0 0]
polo 1438
[0 0 0 0 0]
polo 1439
[0 0 0 0 0]
polo 1440
[0 0 0 0 0]
polo 1441
[0 0 0 0 0]
polo 1442
[0 0 0 0 0]
polo 1443
[0 0 0 0 0]
polo 1444
[0 0 0 0 0]
polo 1445
[0 0 0 0 0]
polo 1446
[0 0 0 0 0]
polo 1447
[0 0 0 0 0]
polo 1448
[0 0 0 0 0]
polo 1449
[0 0 0 0 0]
polo 1450
[0 0 0 0 0]
polo 1451
[0 0 0 0 0]
polo 1452
[0 0 0 0 0]
polo 1453
[0 0 0 0 0]
polo 1454
[0 0 0 0 0]
polo 1455
[0 0 0 0 0]
polo 1456
[0 0 0 0 0]
polo 1457
[0 0 0 0 0]
polo 1458
[0 0 0 0 0]
polo 1459
[0 0 0 0 0]
polo 1460
[0 0 0 0 0]
polo 1461
[0 0 0 0 0]
polo 1462
[0 0 0 0 0]
polo 1463
[0 0 0 0 0]
polo 1464


KeyboardInterrupt: 